### PR TITLE
Updated gem to work with the second version of MusicBrainz Web Service

### PR DESCRIPTION
**Pull request by localhots**

### CODE REVIEW

**Comment by localhots** [comment]
I've changed my mind. I'll continue development in my fork.

**Comment by dwo** [comment]
Cool, what are your plans going ahead? I've been thinking of re-visiting this for a while and getting it up to speed with the new API version.

**Comment by localhots** [comment]
I've got tons of logics parsing mb responses, going to move them into gem. It'll be more convenient.
Common issues are for example with arrays and hashes

```
if release_groups_mb['release_group_list']['release_group'].is_a? Hash
  release_groups_mb['release_group_list']['release_group'] = [release_groups_mb['release_group_list']['release_group']]
end
```

**Comment by localhots** [comment]
Btw, thanks for a great job!

**Pull request closed without merging**
